language: python

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt
  - pip install coveralls

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

script:
  - python setup.py test
  - coverage run --source=exodata setup.py test

after_success:
  coveralls

# blacklist
branches:
  except:
    - images
