language: python

install: "pip install -r requirements.txt --use-mirrors"

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

script:
  - python setup.py test

# blacklist
branches:
  except:
    - images